# This workflow will install Python dependencies and run unit tests with pytest, all on Python 3.6

name: Python Webserver CI

on:
  pull_request:
    branches: [ master, staging ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest python-dotenv
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
      - name: Run unit tests with pytest
        run: |
          pytest tests/logger-tests.py
          pytest tests/sql-tests.py
          pytest tests/vms-tests.py
          pytest tests/monitor-tests.py
