# This workflow will install Python dependencies, run tests and format with Python Black, all on Python 3.6
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Webserver CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Format with Python Black
      run: black .
    - name: Test with pytest
      run: |
        pytest
