# This workflow will install Python dependencies, run unit tests and format with Python Black, all on Python 3.6
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Webapp CI

on:
  push:
    branches: [ master, staging, philippemnoel/unit-tests ]
  pull_request:
    branches: [ master, staging, philippemnoel/unit-tests ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pytest python-dotenv
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Flask App
      run: |
        export FLASK_APP=server.py
        flask run
    - name: Unit tests with pytest
      run: |
        pytest tests/logger-tests.py
      # pytest tests/sql-tests.py
      # pytest tests/vms-tests.py
      # pytest tests/monitor-tests.py
    - name: Format with Python Black
      run: black .
